### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by cfoellmann** [maxchirkov/html-mode-locker#2]
I will add translation support and the German language files.

I recommend to use the new/upcoming translation platform by @markoheijnen http://wp-translate.org (http://wp-translate.org/projects/html-mode-locker) featuring daily pot file regeneration from the github source.

**Comment by cfoellmann** [comment]
I re-did my contributions. This is how it is structured:
- [master](https://github.com/maxchirkov/html-mode-locker)
  - \- [master-update](https://github.com/cfoellmann/html-mode-locker/tree/master-update) :: general additions
  - \- - [feature-oop](https://github.com/cfoellmann/html-mode-locker/tree/feature-oop) :: changed everything into a working class
  - \- - - [feature-oop-notice](https://github.com/cfoellmann/html-mode-locker/tree/feature-oop-notice) :: changed tour to admin_notice

**Comment by maxchirkov** [comment]
Hi Christian,

took me over an hour just to figure out how I can pull your fork's branch into my local branch, so I can merge it later onto the master. I work alone, so I don't have experience of mixing multiple repos.

In any case: from your chart out there it looks like that the latest branch is "feature-oop-notice", but it doesn't exist - I get a 404 error. I pulled "feature-oop" and tested it on my local machine and here are a few things I noticed right away:
1. Activating and de-activating plugin deletes the plugin's settings as well as all the "lock" data for pages that were locked in HTML mode. I realize that you used the deactivation hook to perform those actions, but personally, I prefer not to delete anything on plugin de-activation. A simple website maintenance and trouble-shooting activity can create a disaster when settings and content are deleted (the data on locked posts is a "content" for this plugin). This kind of operations should be done on "uninstall" only. I added uninstall.php file for this purpose. Haven't tested, but it should remove all the options when you click "delete" plugin link.
2. The checkbox for the actual HTML Mode Lock (in the post editor) wasn't reflecting its status - the box was always empty. I think you just forgot to switch checked() echo parameter to true.

I hope I used Git the right way. I have made a new commit and pushed it to master. It's still in 0.5-dev stage. Take a look - if you think it's good enough, I'll change it to stable.

Thanks again for all the work you did, I really appreciate it. BTW, what's your purpose of the contributions? I just wonder what motivates you to contribute to all the plugins that you do? Is this part of your work/school?

**Comment by cfoellmann** [comment]
- If you have questions about Git or GitHub don't hesitate to ask me. I am no real Git(Hub) expert but I know my way around.
- Sorry I forgot to push the feature-oop-notice branch after I made the post - I was not ready at that point and is still not - I will rebase it on the code you did
- (de)activation: you are totally right. Uninstall.php seems to be preferable. Good catch.
- checkbox status: Missed that - another plus for teamwork :+1: 

I will have a look at the current state of the code, test it and finish the proposal for the admin_notice + help-tab replacing the tour (did you see that it is broken in Firefox?)

I love open source and think if you make money with oss you should donate time or money to the project.
I am providing WordPress hosting for customers and want all plugins running to be in the best shape possible. Currently I work on a WordPress hosting platform with a fixed set of plugins to provide a homepage toolbox for non-tech savvy customers and designers. 

ADD:
Every good WP plugin deserves to be OOP today :wink: . It allows to easily extend the functionality by external functions and phpunit tests.
