### ISSUE TITLE
proper add_settings_field implementation

### ISSUE THREAD

**Issue by cfoellmann** [maxchirkov/html-mode-locker#6]
I will work on the proper implementation for add_settings_field to register one field per (custom_)post_type

**Comment by cfoellmann** [comment]
@maxchirkov if you got a minute you could have a look at this implementation https://github.com/cfoellmann/html-mode-locker/tree/feature-fields which is based on this code https://github.com/markoheijnen/wp-no-taxonomy-base/blob/master/wp-no-taxonomy-base.php#L167
I am not sure why but it is not working - I looked at the code for more than an hour but the solution won't come to me :rage:

**Comment by maxchirkov** [comment]
Have you tried dumping the variables' data within the conditions to see if the conditions pass?
